pipeline{
    agentany
    
    stages{
        stage('Deploy') {
            steps {
            sh '''
            oc project RHT_OCP4_DEV_USER-deploy-strategies
            oc start-build greeting-service --follow --wait
            '''
            }
        }
    }
}
